export interface Info {
    sportcount: number
    personal_Carecount: number
    phonescount: number
    accessoriescount: number
    apparelcount: number
    footwearcount: number
    bookscount:number
    bags_Accessoriescount:number
    beltscount:number
    cufflinkscount:number
    eyewear_Accessoriescount:number
    giftcount:number
    glovescount:number
    headwear_Accessoriescount:number
    jewellerycount:number
    walletscount:number
    watches_Accessoriescount:number
    apparel_setcount:number
    bottomwearcount:number
    dresscount:number
    innerwearcount:number
    loungewear_nightwearcount:number
    sareecount:number
    scarvescount:number
    stolescount:number
    tiescount:number
    topwearcount:number
    generalcount:number
    childrencount:number
    classicscount:number
    crimecount:number
    families_relationshipcount:number
    fantasycount:number
    literaturecount:number
    otherscount:number
    romancecount:number
    science_fictioncount:number
    short_storiescount:number
    young_adultscount:number
    flip_flopscount:number
    sandalcount:number
    shoe_accessoriescount:number
    shoescount:number
    sockscount:number
    bath_bodycount:number
    eyescount:number
    fragrancecount:number
    haircount:number
    lipscount:number
    makeupcount:number
    nailscount:number
    skin_carecount:number
    androidcount:number
    applecount:number
    honorcount:number
    huaweicount:number
    nokiacount:number
    onepluscount:number
    oppocount:number
    redmicount:number
    samsungcount:number
    sonycount:number
    vivocount:number
    bags_Sportingcount:number
    eyewear_Sportingcount:number
    headwear_Sportingcount:number
    sports_equipmentcount:number
    watches_Sportingcount:number
    water_bottlecount:number
    accessoriesrated:number
    accessoriestotalliking:number
    accessoriestotalrating:number
    apparelrated:number
    appareltotalliking:number
    appareltotalrating:number
    booksrated:number
    bookstotalliking:number
    bookstotalrating:number
    footwearrated:number
    footweartotalliking:number
    footweartotalrating:number
    personal_Carerated:number
    personal_Caretotalliking:number
    personal_Caretotalrating:number
    phonesrated:number
    phonestotalliking:number
    phonestotalrating:number
    sportrated:number
    sporttotalliking:number
    sporttotalrating:number
    giftsrated:number
    giftstotalliking:number
    gifttotalrating:number
    bags_Accessoriesrated:number
    bags_Accessoriestotalliking:number
    bags_Accessoriestotalrating:number
    beltsrated:number
    beltstotalliking:number
    beltstotalrating:number
    cufflinksrated:number
    cufflinkstotalliking:number
    cufflinkstotalrating:number
    eyewear_Accessoriesrated:number
    eyewear_Accessoriestotalliking:number
    eyewear_Accessoriestotalrating:number
    glovesrated:number
    glovestotalliking:number
    glovestotalrating:number
    headwear_Accessoriesrated:number
    headwear_Accessoriestotalliking:number
    headwear_Accessoriestotalrating:number
    jewelleryrated:number
    jewellerytotalliking:number
    jewellerytotalrating:number
    walletsrated:number
    walletstotalliking:number
    walletstotalrating:number
    watches_Accessoriesrated:number
    watches_Accessoriestotalliking:number
    watches_Accessoriestotalrating:number
    apparel_setrated:number
    apparel_settotalliking:number
    apparel_settotalrating:number
    bottomwearrated:number
    bottomweatotalrrating:number
    bottomweartotalliking:number
    dressrated:number
    dresstotalliking:number
    dresstotalrating:number
    innerwearrated:number
    innerweartotalliking:number
    innerweartotalrating:number
    loungewear_nightwearrated:number
    loungewear_nightweartotalliking:number
    loungewear_nightweartotalrating:number
    sareerated:number
    sareetotalliking:number
    sareetotalrating:number
    scarvesrated:number
    scarvestotalliking:number
    scarvestotalrating:number
    stolesrated:number
    stolestotalliking:number
    stolestotalrating:number
    tiesrated:number
    tiestotalliking:number
    tiestotalrating:number
    topwearrated:number
    topweartotalliking:number
    topweartotalrating:number
    childrenrated:number
    childrentotalliking:number
    childrentotalrating:number
    classicsrated:number
    classicstotalliking:number
    classicstotalrating:number
    crimerated:number
    crimetotalliking:number
    crimetotalrating:number
    families_relationshiprated:number
    families_relationshiptotalliking:number
    families_relationshiptotalrating:number
    fantasyrated:number
    fantasytotalliking:number
    fantasytotalrating:number
    generalrated:number
    generaltotalliking:number
    generaltotalrating:number
    literaturerated:number
    literaturetotalliking:number
    literaturetotalrating:number
    othersrated:number
    otherstotalliking:number
    otherstotalrating:number
    romancerated:number
    romancetotalliking:number
    romancetotalrating:number
    science_fictionrated:number
    science_fictiontotalliking:number
    science_fictiontotalrating:number
    short_storiesrated:number
    short_storiestotalliking:number
    short_storiestotalrating:number
    young_adultsrated:number
    young_adultstotalliking:number
    young_adultstotalrating:number
    flip_flopsrated:number
    flip_flopstotalliking:number
    flip_flopstotalrating:number
    sandalrated:number
    sandaltotalliking:number
    sandaltotalrating:number
    shoe_accessoriesrated:number
    shoe_accessoriestotalliking:number
    shoe_accessoriestotalrating:number
    shoesrated:number
    shoestotalliking:number
    shoestotalrating:number
    socksrated:number
    sockstotalliking:number
    sockstotalrating:number
    bath_bodyrated:number
    bath_bodytotalliking:number
    bath_bodytotalrating:number
    eyesrated:number
    eyestotalliking:number
    eyestotalrating:number
    fragrancerated:number
    fragrancetotalliking:number
    fragrancetotalrating:number
    hairrated:number
    hairtotalliking:number
    hairtotalrating:number
    lipsrated:number
    lipstotalliking:number
    lipstotalrating:number
    makeuprated:number
    makeuptotalliking:number
    makeuptotalrating:number
    nailsrated:number
    nailstotalliking:number
    nailstotalrating:number
    skin_carerated:number
    skin_caretotalliking:number
    skin_caretotalrating:number
    androidrated:number
    androidtotalliking:number
    androidtotalrating:number
    applerated:number
    appletotalliking:number
    appletotalrating:number
    honorrated:number
    honortotalliking:number
    honortotalrating:number
    huaweirated:number
    huaweitotalliking:number
    huaweitotalrating:number
    nokiarated:number
    nokiatotalliking:number
    nokiatotalrating:number
    oneplusrated:number
    oneplustotalliking:number
    oneplustotalrating:number
    opporated:number
    oppototalliking:number
    oppototalrating:number
    redmirated:number
    redmitotalliking:number
    redmitotalrating:number
    samsungrated:number
    samsungtotalliking:number
    samsungtotalrating:number
    sonyrated:number
    sonytotalliking:number
    sonytotalrating:number
    vivorated:number
    vivototalliking:number
    vivototalrating:number
    bags_Sportingrated:number
    bags_Sportingtotalliking:number
    bags_Sportingtotalrating:number
    eyewear_Sportingrated:number
    eyewear_Sportingtotalliking:number
    eyewear_Sportingtotalrating:number
    headwear_Sportingrated:number
    headwear_Sportingtotalliking:number
    headwear_Sportingtotalrating:number
    sports_equipmentrated:number
    sports_equipmenttotalliking:number
    sports_equipmenttotalrating:number
    watches_Sportingrated:number
    watches_Sportingtotalliking:number
    watches_Sportingtotalrating:number
    water_bottlerated:number
    water_bottletotalliking:number
    water_bottletotalrating:number
}